dependencies:
- python=3.9
- APScheduler==3.9.1.post1
- certifi==2022.9.24
- charset-normalizer==2.1.1
- click==8.1.3
- Flask==2.2.2
- Flask-APScheduler==1.12.4
- flask-oidc==1.4.0
- greenlet==2.0.1
- httplib2==0.21.0
- idna==3.4
- importlib-metadata==5.1.0
- itsdangerous==2.0.0
- Jinja2==3.1.2
- MarkupSafe==2.1.1
- oauth2client==4.1.3
- pyasn1==0.4.8
- pyasn1-modules==0.2.8
- pyparsing==3.0.9
- python-dateutil==2.8.2
- pytz==2022.6
- pytz-deprecation-shim==0.1.0.post0
- requests==2.28.1
- rsa==4.9
- schedule==1.1.0
- six==1.16.0
- SQLAlchemy==1.4.44
- tzdata==2022.7
- tzlocal==4.2
- urllib3==1.26.13
- Werkzeug==2.2.2
- zipp==3.11.0

